#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sat Oct 03 06:19:35 UTC 2026
prefixes-apache.snapshots.txt.lastUpdated=1791008374842
prefixes-central-snapshots.txt.error=
prefixes-central-snapshots.txt.lastUpdated=1791008375689
prefixes-central.txt.lastUpdated=1791008373006
prefixes-sonatype-nexus-snapshots.txt.error=
prefixes-sonatype-nexus-snapshots.txt.lastUpdated=1791008375370
